apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SECRET_KEY: "your-super-secret"
  JWT_SECRET: "secret-key"  # pora hora nada
  DATABASE_URL: "postgres://postgres:postgres@supabase-db:5432/postgres"
