version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  supabase-db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  # Puedes agregar aquí uno de los microservicios
  auth:
    build: ./services/auth
    depends_on:
      - rabbitmq
      - supabase-db
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
      DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
    ports:
      - "8000:8000"
