apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

bases:
  - ../../base/auth

patches:
  - target:
      kind: Deployment
      name: auth
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: muratsuky/auth:latest